apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- csidriver.yaml
- storageclass.yaml
- daemonset.yaml

images:
- name: csi-driver
  newName: quay.io/zncdatadev/secret-csi-driver
  newTag: 0.0.0-dev
