apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: secrets.zncdata.dev
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: secret-operator
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/managed-by: kustomize
provisioner: secrets.zncdata.dev
